/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AbitaDash API
 * Public API for AbitaDash - Categories and Products
 * OpenAPI spec version: 1.0.0
 */
import type { GetCategories200DataItem } from './getCategories200DataItem';

export type GetCategories200 = {
  data?: GetCategories200DataItem[];
};
