/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AbitaDash API
 * Public API for AbitaDash - Categories and Products
 * OpenAPI spec version: 1.0.0
 */
import type { GetCategoriesCategorySlugProducts200DataItem } from './getCategoriesCategorySlugProducts200DataItem';

export type GetCategoriesCategorySlugProducts200 = {
  data?: GetCategoriesCategorySlugProducts200DataItem[];
};
