/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AbitaDash API
 * Public API for AbitaDash - Categories and Products
 * OpenAPI spec version: 1.0.0
 */

export type GetProductsProductSlug200Data = {
  id?: number;
  name?: string;
  slug?: string;
  description?: string;
  imageUrl?: string;
  categoryId?: number;
};
