/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AbitaDash API
 * Public API for AbitaDash - Categories and Products
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductsProductSlug200Data } from './getProductsProductSlug200Data';
import type { GetProductsProductSlug200RelatedProductsItem } from './getProductsProductSlug200RelatedProductsItem';

export type GetProductsProductSlug200 = {
  data?: GetProductsProductSlug200Data;
  relatedProducts?: GetProductsProductSlug200RelatedProductsItem[];
};
