/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AbitaDash API
 * Public API for AbitaDash - Categories and Products
 * OpenAPI spec version: 1.0.0
 */
import type { GetProducts200DataItem } from './getProducts200DataItem';

export type GetProducts200 = {
  data?: GetProducts200DataItem[];
};
