/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AbitaDash API
 * Public API for AbitaDash - Categories and Products
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetCategoriesCategorySlugProducts200,
  GetProducts200,
  GetProductsProductSlug200,
} from "../models";

import { buildApiUrl } from "../base-url";

/**
 * Retrieve all products
 * @summary Get all products
 */
export type getProductsResponse200 = {
  data: GetProducts200;
  status: 200;
};

export type getProductsResponseSuccess = getProductsResponse200 & {
  headers: Headers;
};
export type getProductsResponse = getProductsResponseSuccess;

export const getGetProductsUrl = () => {
  return buildApiUrl("/products");
};

export const getProducts = async (
  options?: RequestInit
): Promise<getProductsResponse> => {
  const res = await fetch(getGetProductsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProductsResponse;
};

export const getGetProductsQueryKey = () => {
  return [getGetProductsUrl()] as const;
};

export const getGetProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({
    signal,
  }) => getProducts({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProducts>>
>;
export type GetProductsQueryError = unknown;

export function useGetProducts<
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProducts<
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProducts<
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all products
 */

export function useGetProducts<
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProductsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve all products for a specific category by its slug
 * @summary Get products by category
 */
export type getCategoriesCategorySlugProductsResponse200 = {
  data: GetCategoriesCategorySlugProducts200;
  status: 200;
};

export type getCategoriesCategorySlugProductsResponse404 = {
  data: void;
  status: 404;
};

export type getCategoriesCategorySlugProductsResponseSuccess =
  getCategoriesCategorySlugProductsResponse200 & {
    headers: Headers;
  };
export type getCategoriesCategorySlugProductsResponseError =
  getCategoriesCategorySlugProductsResponse404 & {
    headers: Headers;
  };

export type getCategoriesCategorySlugProductsResponse =
  | getCategoriesCategorySlugProductsResponseSuccess
  | getCategoriesCategorySlugProductsResponseError;

export const getGetCategoriesCategorySlugProductsUrl = (
  categorySlug: string
) => {
  return buildApiUrl(`/categories/${categorySlug}/products`);
};

export const getCategoriesCategorySlugProducts = async (
  categorySlug: string,
  options?: RequestInit
): Promise<getCategoriesCategorySlugProductsResponse> => {
  const res = await fetch(
    getGetCategoriesCategorySlugProductsUrl(categorySlug),
    {
      ...options,
      method: "GET",
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCategoriesCategorySlugProductsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getCategoriesCategorySlugProductsResponse;
};

export const getGetCategoriesCategorySlugProductsQueryKey = (
  categorySlug: string
) => {
  return [getGetCategoriesCategorySlugProductsUrl(categorySlug)] as const;
};

export const getGetCategoriesCategorySlugProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
  TError = void,
>(
  categorySlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCategoriesCategorySlugProductsQueryKey(categorySlug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>
  > = ({ signal }) =>
    getCategoriesCategorySlugProducts(categorySlug, {
      signal,
      ...fetchOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!categorySlug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCategoriesCategorySlugProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>
>;
export type GetCategoriesCategorySlugProductsQueryError = void;

export function useGetCategoriesCategorySlugProducts<
  TData = Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
  TError = void,
>(
  categorySlug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
          TError,
          Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategoriesCategorySlugProducts<
  TData = Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
  TError = void,
>(
  categorySlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
          TError,
          Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategoriesCategorySlugProducts<
  TData = Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
  TError = void,
>(
  categorySlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get products by category
 */

export function useGetCategoriesCategorySlugProducts<
  TData = Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
  TError = void,
>(
  categorySlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoriesCategorySlugProducts>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCategoriesCategorySlugProductsQueryOptions(
    categorySlug,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve a single product by slug with 3 random related products from the same category
 * @summary Get product with related products
 */
export type getProductsProductSlugResponse200 = {
  data: GetProductsProductSlug200;
  status: 200;
};

export type getProductsProductSlugResponse404 = {
  data: void;
  status: 404;
};

export type getProductsProductSlugResponseSuccess =
  getProductsProductSlugResponse200 & {
    headers: Headers;
  };
export type getProductsProductSlugResponseError =
  getProductsProductSlugResponse404 & {
    headers: Headers;
  };

export type getProductsProductSlugResponse =
  | getProductsProductSlugResponseSuccess
  | getProductsProductSlugResponseError;

export const getGetProductsProductSlugUrl = (productSlug: string) => {
  return buildApiUrl(`/products/${productSlug}`);
};

export const getProductsProductSlug = async (
  productSlug: string,
  options?: RequestInit
): Promise<getProductsProductSlugResponse> => {
  const res = await fetch(getGetProductsProductSlugUrl(productSlug), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsProductSlugResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProductsProductSlugResponse;
};

export const getGetProductsProductSlugQueryKey = (productSlug: string) => {
  return [getGetProductsProductSlugUrl(productSlug)] as const;
};

export const getGetProductsProductSlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductsProductSlug>>,
  TError = void,
>(
  productSlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsProductSlug>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProductsProductSlugQueryKey(productSlug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProductsProductSlug>>
  > = ({ signal }) =>
    getProductsProductSlug(productSlug, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!productSlug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductsProductSlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProductsProductSlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProductsProductSlug>>
>;
export type GetProductsProductSlugQueryError = void;

export function useGetProductsProductSlug<
  TData = Awaited<ReturnType<typeof getProductsProductSlug>>,
  TError = void,
>(
  productSlug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsProductSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsProductSlug>>,
          TError,
          Awaited<ReturnType<typeof getProductsProductSlug>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductsProductSlug<
  TData = Awaited<ReturnType<typeof getProductsProductSlug>>,
  TError = void,
>(
  productSlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsProductSlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsProductSlug>>,
          TError,
          Awaited<ReturnType<typeof getProductsProductSlug>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductsProductSlug<
  TData = Awaited<ReturnType<typeof getProductsProductSlug>>,
  TError = void,
>(
  productSlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsProductSlug>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get product with related products
 */

export function useGetProductsProductSlug<
  TData = Awaited<ReturnType<typeof getProductsProductSlug>>,
  TError = void,
>(
  productSlug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProductsProductSlug>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProductsProductSlugQueryOptions(
    productSlug,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
